- name: install apache2
  become: "yes"
  apt: name=apache2 update_cache=yes state=latest

- name: install PHP module for Apache
  apt: name=libapache2-mod-php5 state=present
  become: "yes"

- name: enabled mod_rewrite
  become: "yes"
  apache2_module: name=rewrite state=present

- name: install php and some other dependencies
  become: "yes"
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - php5
      - php5-cli
      - php5-common
      - php5-curl
      - php5-dev
      - php5-gd
      - php5-mysql
      - php5-xsl
      - php5-mcrypt
      - php5-intl
      - php5-fpm
      - apache2-mpm-worker
      - libapache2-mod-macro
      - libapache2-mod-fastcgi
      - git

- name: install mysql 5.5
  become: "yes"
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: "yes"
  with_items:
      - mysql-server-5.5
      - python-mysqldb

- name: add a user 'mysqluser' with all priviledge
  become: "yes"
  mysql_user:
    name: mysqluser
    host: '%'
    password: "mysqlpassword"
    priv: '*.*:ALL'
    state: present

- name: open firewall port
  become: "yes"
  ufw:
    port: 3306
    proto: tcp
    rule: allow

- name: configure mysql
  become: "yes"
  service:
    name: mysql
    state: restarted