---
- name: Updating APT cache
  apt: update_cache=yes

- name: install php and some other dependencies
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - git
      - mcrypt
      - nginx
      - php5-cli
      - php5-curl
      - php5-fpm
      - php5-intl
      - php5-json
      - php5-mcrypt
      - php5-mysql

- name: ensure php5-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify:
    - restart php5-fpm
    - restart nginx

- name: enable php5 mcrypt module
  shell: php5enmod mcrypt
  args:
    creates: /etc/php5/cli/conf.d/20-mcrypt.ini

- name: install mysql 5.5
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: "yes"
  with_items:
      - mysql-server-5.5
      - python-mysqldb

- name: add a user 'mysqluser' with all priviledge
  mysql_user:
    name: mysqluser
    host: '%'
    password: "mysqlpassword"
    priv: '*.*:ALL'
    state: present

- name: open firewall port
  ufw:
    port: 3306
    proto: tcp
    rule: allow

- name: configure mysql
  service:
    name: mysql
    state: restarted

- name: create ssl folder
  become: "yes"
  file:
    path: "/etc/nginx/ssl"
    state: directory

- name: copy ssl private key
  copy:
    src: files/ssl/local-transport.local.key
    dest: /etc/nginx/ssl/local-transport.local.key

- name: copy ssl certificates
  copy:
    src: files/ssl/local-transport.local.crt
    dest: /etc/nginx/ssl/local-transport.local.crt
#
#- name: enable ssl on apache
#  command: a2enmod ssl
