---
- name: Updating APT cache
  apt: update_cache=yes

- name: install apache2
  apt: name=apache2 update_cache=yes state=latest

- name: install PHP module for Apache
  apt: name=libapache2-mod-php5 state=present

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present

- name: install php and some other dependencies
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - php5
      - php5-cli
      - php5-common
      - php5-curl
      - php5-dev
      - php5-gd
      - php5-mysql
      - php5-xsl
      - php5-mcrypt
      - php5-intl
      - php5-fpm
      - apache2-mpm-worker
      - libapache2-mod-macro
      - libapache2-mod-fastcgi
      - git

- name: install mysql 5.5
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: "yes"
  with_items:
      - mysql-server-5.5
      - python-mysqldb

- name: add a user 'mysqluser' with all priviledge
  mysql_user:
    name: mysqluser
    host: '%'
    password: "mysqlpassword"
    priv: '*.*:ALL'
    state: present

- name: open firewall port
  ufw:
    port: 3306
    proto: tcp
    rule: allow

- name: configure mysql
  service:
    name: mysql
    state: restarted

- name: copy ssl private key
  copy:
    src: files/ssl/local-transport.local.key
    dest: /etc/ssl/private/local-transport.local.key

- name: copy ssl certificates
  copy:
    src: files/ssl/local-transport.local.crt
    dest: /etc/ssl/certs/local-transport.local.crt

- name: enable ssl on apache
  command: a2enmod ssl