- name: install lamp packages
  become: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - php5
      - php5-cli
      - php5-common
      - php5-curl
      - php5-dev
      - php5-gd
      - php5-mysql
      - php5-xsl
      - php5-mcrypt
      - php5-intl
      - php5-fpm
      - apache2-mpm-worker
      - libapache2-mod-macro
      - libapache2-mod-fastcgi
